### PR TITLE
Added Find_Common_Element_in_matrix.cpp file and fixed issue-#4279

### LINKED ISSUE #4279: Find common element in row-wise sorted matrix in C++
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

### PR DESCRIPTION
**Pull request by CSAURABH**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
Added Find_Common_Element_in_matrix.cpp file and fixed issue-#4279
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Fixes #4279

### CODE REVIEW

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+        4 5 0 2 3
+    
+    Output :
+        Common element is : 5
+        Common element is : 3
+        No Common element
+    
+    Time complexity: O(r*c)
+    Space Complexity: O(1)
+*/
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Add a new line at the EOF

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+    Output 1 : Common element is : 5
+
+    Example 2 :
+
+    Input 2 : 2 4 3 8 7
+              1 3 5 6 8
+              1 2 3 1 3
+              4 5 0 2 3
+    
+    Output 2 : No Common element
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Remove this

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+    Step2 : Insert elements of the first row and initialize them with 
+            a value of 1 and Check if the current element in the map
+            and first in the current row Update the value of this key 
+            in HashTable with current row number
+        
+    Step3 : Iterate over HashTable and print all those keys for 
+            which value = 1 
+*/
+
+//CODE :-
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Remove this

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+#include<bits/stdc++.h>
+using namespace std;
+
+// Function to find common element in the matrix
+int solve()
+{
+    // Input r = size of row.
+    // Input c = size of column.
+    int r,c;
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Use meaningful variable names

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+    for (int i = 0; i < r; ++i)
+    {
+        for (int j = 0; j < c; ++j)
+        {
+            cin >> a[i][j];
+        }
+    }
+    
+    // Create a hash map to store 
+    // count of element
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Use multi-line comments

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+    unordered_map<int, int> count;
+  
+    for (int i = 0; i < r; i++) {
+        
+        for (int j = 1; j < c; j++) {
+
+            // Insert elements of the first row and
+            // initialize them with a value of 1
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Use multi-line comments

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+            if (i == 0) {
+                count[a[0][i]] = 1;
+            }
+            
+            // Check if the current element exists
+            // in the map and first in the current row
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Use multi-line comments

File: C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+
+    // Return the element having a count not equal to 1
+    return -1;
+}
+
+int main()
+{
+    // Input the test cases.
+    int t;
+    cin >> t;
```
Comment (HarshCasper) [inline C-Plus-Plus/other/Find_Common_Element_in_matrix.cpp]: Remove test cases stuff. We are not in a CP contest

**Review by HarshCasper — CHANGES_REQUESTED** [review]

**Review by HarshCasper — APPROVED** [review]
